
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package at.jku.ce.airline.service;

//import java.util.List;
import java.util.logging.Logger;
/*
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
*/
import at.jku.ce.airline.bl.AirlinePlatformService;

/**
 * This class was generated by Apache CXF 2.3.7
 * 2014-12-24T12:09:32.315+01:00
 * Generated source version: 2.3.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "AirlineServiceImplService",
                      portName = "AirlineServiceImplPort",
                      targetNamespace = "http://service.airline.ce.jku.at/",
                      wsdlLocation = "http://140.78.73.67:8080/AirlineService/services/airlineservice?wsdl",
                      endpointInterface = "at.jku.ce.airline.service.AirlineServiceImpl")
                      
public class AirlineServiceImplImpl implements AirlineServiceImpl {

    private static final Logger LOG = Logger.getLogger(AirlineServiceImplImpl.class.getName());
    
    
    /* (non-Javadoc)
     * @see at.jku.ce.airline.service.AirlineServiceImpl#getFlight(java.lang.String  flightId )*
     */
    public at.jku.ce.airline.service.Flight getFlight(java.lang.String flightId) { 
        LOG.info("Executing operation getFlight");
        try {
        	return AirlinePlatformService.getInstance().getFlightById(flightId);
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see at.jku.ce.airline.service.AirlineServiceImpl#getFlightplan(*
     */
    public java.util.List<at.jku.ce.airline.service.Flight> getFlightplan() { 
        LOG.info("Executing operation getFlightplan");
        try {
        	return AirlinePlatformService.getInstance().getAirline().getFlightPlan();
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see at.jku.ce.airline.service.AirlineServiceImpl#getAirline(*
     */
    public at.jku.ce.airline.service.Airline getAirline() { 
        LOG.info("Executing operation getAirline");
        try {
        	return AirlinePlatformService.getInstance().getAirline();
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see at.jku.ce.airline.service.AirlineServiceImpl#bookFlight(java.lang.String  bookingUuid ,)java.lang.String  flightId ,)javax.xml.datatype.XMLGregorianCalendar  flightDate )*
     */
    public boolean bookFlight(java.lang.String bookingUuid,java.lang.String flightId,javax.xml.datatype.XMLGregorianCalendar flightDate) { 
        LOG.info("Executing operation bookFlight");
                
        try {
            return AirlinePlatformService.getInstance().performBooking(bookingUuid, flightId, flightDate);
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
            
        }
    }

    /* (non-Javadoc)
     * @see at.jku.ce.airline.service.AirlineServiceImpl#cancelFlight(java.lang.String  bookingUuid ,)java.lang.String  flightId )*
     */
    public boolean cancelFlight(java.lang.String bookingUuid,java.lang.String flightId) { 
        LOG.info("Executing operation cancelFlight");
               
        try {
        	return AirlinePlatformService.getInstance().cancelBooking(bookingUuid,flightId);
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }
}
    /* public static void main(String[] args){
    	AirlineServiceImplImpl impl = new AirlineServiceImplImpl();
    	//Airline a = impl.getAirline();
    	impl.getAirline();
    	List<Flight> p = impl.getFlightplan();
    
    	
    /*	for(Flight f : p){
    	
    			 System.out.println("---- Flight ----");
    			 System.out.println(f.getFlightId());
    			 System.out.println(f.getPlaneName());
    			 System.out.println(f.getStdFee());
    			 System.out.println("---- Arrives At ----");
    			 System.out.println(f.getArrivesAt().getCity());
    			 System.out.println(f.getArrivesAt().getCountry());
    			 System.out.println(f.getArrivesAt().getIcao());
    			 System.out.println(f.getArrivesAt().getName());
    			 System.out.println(f.getArrivesAt().getAirportTax());
    			 System.out.println("---- Departes From ----");
    			 System.out.println(f.getDepartesFrom().getCity());
    			 System.out.println(f.getDepartesFrom().getCountry());
    			 System.out.println(f.getDepartesFrom().getIcao());
    			 System.out.println(f.getDepartesFrom().getName());
    			 System.out.println(f.getDepartesFrom().getAirportTax());
    			 System.out.println("---- Arrives On ----");
    			 System.out.println(f.getArrivalTime().getIndexDayOfWeek());
    			 System.out.println(f.getArrivalTime().getTimeOfDay());
    			 System.out.println("---- Departes On ----");
    			 System.out.println(f.getDepartureTime().getIndexDayOfWeek());
    			 System.out.println(f.getDepartureTime().getTimeOfDay());
    	}*/